name: GodPlugin
version: 1.0
author: PyroMageEx
main: me.PyroMageEx.GodPlugin.Main
description: zzz

commands:
  jail:
    description: Surrounds a target in a bedrock prison
    usage: |
      /<command> [player]
  scaffold:
    description: Temporarily scaffolds for a player
    usage: |
      /<command> [player]
  bubble:
    description: Creates an under water bubble for the player
    usage: |
      /<command> [player]
  splash:
    description: 50/50 Splashes someone with either good or bad effects
    usage: |
      /<command> [player]
  swapinv:
    description: swaps the inventories of two players
    usage: |
      /<command> [player1] [player2]
  remheld:
    description: removes the held item of a player
    usage: |
      /<command> [player]