name: GodPlugin
version: 1.0
author: PyroMageEx
main: me.PyroMageEx.GodPlugin.Main
description: zzz

commands:
  jail:
    description: Surrounds a target in a bedrock prison
    usage: |
      /<command> [player]
  scaffold:
    description: Temporarily scaffolds for a player
    usage: |
      /<command> [player]
  bubble:
    description: Creates an underwater bubble for the player
    usage: |
      /<command> [on/off] [player]